project:
  type: website
  output-dir: docs

website:
  title: "Hazard Systems Research Group"
  favicon: assets/logo.png
  description: "AI-enabled multihazard forecasting, early warning systems, and response"
  navbar:
    logo: assets/logo.png
    right:
      - text: About
        href: about.qmd
      - text: People
        href: people.qmd
      - text: Publications
        href: publications.qmd
      - text: Projects
        href: projects.qmd
      - text: Join Us
        href: join-us.qmd
      # - text: Posts
      #   href: posts/
  page-footer:
    center: |
      © 2026 Hazard Systems Research Group · Built with Quarto · Hosted on GitHub Pages

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

metadata-files:
  - _meta.yml
